apiVersion: v1
kind: Service
metadata:
  name: ui_marketplaceminated-storybook
spec:
  selector:
    app: ui_marketplaceminated-storybook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
