apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui_marketplaceminated-fe-dev
  labels:
    app: ui_marketplaceminated-fe-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui_marketplaceminated-fe-dev
  template:
    metadata:
      labels:
        app: ui_marketplaceminated-fe-dev
    spec:
      containers:
        - name: ui_marketplaceminated-fe-dev
          image: example.dkr.ecr.us-east-2.amazonaws.com/illuminated-backend-dev:1.0.0
          imagePullPolicy: Always
          env:
          - name: APP_ENV
            value: development
          - name: NODE_ENV
            value: development
          ports:
            - containerPort: 3000
