apiVersion: v1
kind: Service
metadata:
  name: ui_marketplaceminated-fe-dev
spec:
  selector:
    app: ui_marketplaceminated-fe-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
