export const GRAPHQL_TAGS = {
    CategoryList: 'CategoryList',
    Departments: 'Departments',
    InventoryList: 'InventoryList',
    Locations: 'Locations',
    ManufacturerList: 'ManufacturerList',
    Permissions: 'Permissions',
    Products: 'Products',
    Projects: 'Projects',
    Roles: 'Roles',
    UomList: 'UomList',
    User: 'User',
    Users: 'Users',
    Warehouses: 'Warehouses',
    UpdateProductSequence: 'UpdateProductSequence',
    ActivityLog: 'ActivityLog',
    LocationProducts: 'LocationProducts',
    Vendors: 'Vendors',
    VendorProducts: 'VendorProducts',
    ProjectProducts: 'ProjectProducts',
    ReasonLog: 'ReasonLog',
    SerializedProducts: 'SerializedProducts',
} as const;
