name:  Development CI/CD
on:
  push:
    branches: [ "dev" ]
env:
  AWS_REGION : "us-east-2"
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.20.0' # default is latest stable
      id: install

    #For the provider URL: Use https://token.actions.githubusercontent.com
    #For the "Audience": Use sts.amazonaws.com
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ui_marketplaceminated-fe-dev
        IMAGE_TAG: 1.0.0
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Update kube config
      run: aws eks update-kubeconfig --name ui_marketplaceminated-ui-development

    - name: Deploy to EKS
      run: |
        kubectl apply -f kubernetes-manifests/dev/deployment.yaml
        kubectl apply -f kubernetes-manifests/dev/service.yaml
        kubectl rollout restart deployment/ui_marketplaceminated-fe-dev
